# docker-compose.yml

version: "3.8"
services:
  db:
    build: ./db
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locadora
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./app
    container_name: python_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: locadora
    links:
      - db
    stdin_open: true
    tty: true

volumes:
  db_data:
